### ISSUE TITLE
Prefix Loss & Prefix Not Loading sometimes

### ISSUE THREAD

**Issue by Marcus101RR** [Enerdy/InvSee#3]
Issue 1: When viewing another player's inventory, it fails to load the prefixes occasionally, and requires you to reuse the command twice or more to finally get their prefixes.

Issue 2: When restoring your own inventory, your prefixes are gone for good. This was fixed in TsHock apparently, but still affects Invsee.

**Comment by AxisKriel** [comment]
Both issues are related to prefixes -- those have always been a pain in the ass to deal with. I'll try to look into this asap, now that prefixes have been supposedly "fixed" in TShock. Bump this up if I haven't given feedback in a week so that this doesn't die off like most of the issues pointed at my repos do :/.

**Comment by Marcus101RR** [comment]
I tested it out a bit, and its 90% success and 10% loss, seems to happen very rarely now, mainly because it uses the new tshock that I am using which has this prefix loss fixed. So far, I will keep testing, but it seems to be there, just very rarely.

**Comment by AxisKriel** [comment]
Closing this as @Marcus101RR's issue seems to be fixed and I haven't received any new reports in 23 days.
